In [88]:
from sklearn.preprocessing import normalize
import pandas as pd
from sklearn.metrics import pairwise_distances as ps

In [89]:
df_h = pd.read_excel(r"C:\Users\momoj\Desktop\Data sinence\AmesHousing.xlsx")
df_housing_quant = df_h[["Bedroom AbvGr", "Gr Liv Area"]].copy()
df_housing_quant["Bathrooms"] = (
    df_h["Full Bath"] +
    0.5 * df_h["Half Bath"]
)
df_housing_quant.head(2)

   Bedroom AbvGr  Gr Liv Area  Bathrooms
0              3         1656        1.0
1              2          896        1.0

In [90]:

# ملاحظة: نستخدم axis=0 لأننا نريد عمل scale للمتغيرات (الخائص) وليس للصفوف
df_housing_norm_array = normalize(df_housing_quant, axis=0)
df_housing_norm_array = pd.DataFrame(df_housing_norm_array, 
                                                     index=df_housing_quant.index)
print(df_housing_norm_array)
print('*'*90)
# # الزوج الأول:
dist_1 = ps(df_housing_norm.loc[[2927]], df_housing_norm.loc[[2928]])
print(dist_1,"\n",'*'*90)
# # الزوج الثاني: 
dist_2 = ps(df_housing_norm.loc[[2498]], df_housing_norm.loc[[290]])
print(dist_2)
print(f"Distance (2927 vs 2928) Normalized: {dist_1[0][0]:.4f}")
print(f"Distance (2498 vs 290) Normalized: {dist_2[0][0]:.4f}")

             0         1         2
0     0.018649  0.019331  0.009878
1     0.012433  0.010460  0.009878
2     0.018649  0.015514  0.014817
3     0.018649  0.024631  0.024695
4     0.018649  0.019016  0.024695
...        ...       ...       ...
2925  0.018649  0.011709  0.009878
2926  0.012433  0.010530  0.009878
2927  0.018649  0.011323  0.009878
2928  0.012433  0.016215  0.009878
2929  0.018649  0.023347  0.024695

[2930 rows x 3 columns]
******************************************************************************************
[[0.00791002]]
 ******************************************************************************************
[[0.02110395]]
Distance (2927 vs 2928) Normalized: 0.0079
Distance (2498 vs 290) Normalized: 0.0211

In [91]:
from sklearn.preprocessing import MinMaxScaler

# 1. تطبيق Min-Max Scaling
scaler = MinMaxScaler()
df_housing_minmax_array = scaler.fit_transform(df_housing_quant)
df_housing_minmax = pd.DataFrame(df_housing_minmax_array, 
                                 columns=df_housing_quant.columns, 
                                 index=df_housing_quant.index)
print(df_housing_minmax_array,"\n",'*'*75)
print(df_housing_minmax)

[[0.375      0.24905803 0.2       ]
 [0.25       0.10587792 0.2       ]
 [0.375      0.1874529  0.3       ]
 ...
 [0.375      0.11981914 0.2       ]
 [0.25       0.19875659 0.2       ]
 [0.375      0.31386586 0.5       ]]
 ***************************************************************************
      Bedroom AbvGr  Gr Liv Area  Bathrooms
0             0.375     0.249058        0.2
1             0.250     0.105878        0.2
2             0.375     0.187453        0.3
3             0.375     0.334589        0.5
4             0.375     0.243971        0.5
...             ...          ...        ...
2925          0.375     0.126036        0.2
2926          0.250     0.107008        0.2
2927          0.375     0.119819        0.2
2928          0.250     0.198757        0.2
2929          0.375     0.313866        0.5

[2930 rows x 3 columns]

In [92]:
dist_1_mm = ps(df_housing_minmax.loc[[2927]], df_housing_minmax.loc[[2928]])
dist_2_mm = ps(df_housing_minmax.loc[[2498]], df_housing_minmax.loc[[290]])
print(f"dist_1mm\n{dist_1_mm}, \n{'*'*15} \ndist_2mm \n{dist_2_mm}\n ","*"*15)


print(f"Distance (2927 vs 2928) Min-Max: {dist_1_mm[0][0]:.5f}")
print(f"Distance (2498 vs 290) Min-Max: {dist_2_mm[0][0]:.5f}")

dist_1mm
[[0.14783816]],
***************
dist_2mm
[[0.42500067]]
  ***************
Distance (2927 vs 2928) Min-Max: 0.14784
Distance (2498 vs 290) Min-Max: 0.42500

In [93]:
df_full = df_h.copy()
#i taked a copy😎
print(df_full)

      Order        PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street  \
0         1  526301100           20        RL         141.0     31770   Pave
1         2  526350040           20        RH          80.0     11622   Pave
2         3  526351010           20        RL          81.0     14267   Pave
3         4  526353030           20        RL          93.0     11160   Pave
4         5  527105010           60        RL          74.0     13830   Pave
...     ...        ...          ...       ...           ...       ...    ...
2925   2926  923275080           80        RL          37.0      7937   Pave
2926   2927  923276100           20        RL           NaN      8885   Pave
2927   2928  923400125           85        RL          62.0     10441   Pave
2928   2929  924100070           20        RL          77.0     10010   Pave
2929   2930  924151050           60        RL          74.0      9627   Pave

     Alley Lot Shape Land Contour  ... Pool Area Pool QC  Fence Misc Feature  \
0      NaN       IR1          Lvl  ...         0     NaN    NaN          NaN
1      NaN       Reg          Lvl  ...         0     NaN  MnPrv          NaN
2      NaN       IR1          Lvl  ...         0     NaN    NaN         Gar2
3      NaN       Reg          Lvl  ...         0     NaN    NaN          NaN
4      NaN       IR1          Lvl  ...         0     NaN  MnPrv          NaN
...    ...       ...          ...  ...       ...     ...    ...          ...
2925   NaN       IR1          Lvl  ...         0     NaN  GdPrv          NaN
2926   NaN       IR1          Low  ...         0     NaN  MnPrv          NaN
2927   NaN       Reg          Lvl  ...         0     NaN  MnPrv         Shed
2928   NaN       Reg          Lvl  ...         0     NaN    NaN          NaN
2929   NaN       Reg          Lvl  ...         0     NaN    NaN          NaN

     Misc Val Mo Sold Yr Sold Sale Type  Sale Condition  SalePrice
0           0       5    2010       WD           Normal     215000
1           0       6    2010       WD           Normal     105000
2       12500       6    2010       WD           Normal     172000
3           0       4    2010       WD           Normal     244000
4           0       3    2010       WD           Normal     189900
...       ...     ...     ...       ...             ...        ...
2925        0       3    2006       WD           Normal     142500
2926        0       6    2006       WD           Normal     131000
2927      700       7    2006       WD           Normal     132000
2928        0       4    2006       WD           Normal     170000
2929        0      11    2006       WD           Normal     188000

[2930 rows x 82 columns]

In [94]:

# تحويل المتغيرات النصية إلى Dummy Variables (One-Hot Encoding)
df_encoded = pd.get_dummies(df_full)
#               print(df_encoded)باديه

# ملء القيم المفقودة بـ 0 (لأن المسافة لا تعمل مع NaN)
df_encoded = df_encoded.fillna(0) 
#    2. عمل Scaling للبيانات
scaler = MinMaxScaler()
df_scaled_array = scaler.fit_transform(df_encoded)
print(df_scaled_array,'\n',"*"*90)
df_scaled = pd.DataFrame(df_scaled_array, index=df_encoded.index, columns=df_encoded.columns)
print(df_scaled)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 [3.41413452e-04 1.01788895e-04 0.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 [6.82826903e-04 1.03806370e-04 0.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 ...
 [9.99317173e-01 8.25914814e-01 3.82352941e-01 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 [9.99658587e-01 8.27370610e-01 0.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 [1.00000000e+00 8.27476641e-01 2.35294118e-01 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]]
 ******************************************************************************************
         Order       PID  MS SubClass  Lot Frontage  Lot Area  Overall Qual  \
0     0.000000  0.000000     0.000000      0.450479  0.142420      0.555556
1     0.000341  0.000102     0.000000      0.255591  0.048246      0.444444
2     0.000683  0.000104     0.000000      0.258786  0.060609      0.555556
3     0.001024  0.000108     0.000000      0.297125  0.046087      0.666667
4     0.001366  0.001672     0.235294      0.236422  0.058566      0.444444
...        ...       ...          ...           ...       ...           ...
2925  0.998634  0.825655     0.352941      0.118211  0.031022      0.555556
2926  0.998976  0.825657     0.000000      0.000000  0.035453      0.444444
2927  0.999317  0.825915     0.382353      0.198083  0.042726      0.444444
2928  0.999659  0.827371     0.000000      0.246006  0.040711      0.444444
2929  1.000000  0.827477     0.235294      0.236422  0.038921      0.666667

      Overall Cond  Year Built  Year Remod/Add  Mas Vnr Area  ...  \
0            0.500    0.637681        0.166667       0.07000  ...
1            0.625    0.644928        0.183333       0.00000  ...
2            0.625    0.623188        0.133333       0.06750  ...
3            0.500    0.695652        0.300000       0.00000  ...
4            0.500    0.905797        0.800000       0.00000  ...
...            ...         ...             ...           ...  ...
2925         0.625    0.811594        0.566667       0.00000  ...
2926         0.500    0.804348        0.550000       0.00000  ...
2927         0.500    0.869565        0.700000       0.00000  ...
2928         0.500    0.739130        0.416667       0.00000  ...
2929         0.500    0.876812        0.733333       0.05875  ...

      Sale Type_New  Sale Type_Oth  Sale Type_VWD  Sale Type_WD   \
0               0.0            0.0            0.0            1.0
1               0.0            0.0            0.0            1.0
2               0.0            0.0            0.0            1.0
3               0.0            0.0            0.0            1.0
4               0.0            0.0            0.0            1.0
...             ...            ...            ...            ...
2925            0.0            0.0            0.0            1.0
2926            0.0            0.0            0.0            1.0
2927            0.0            0.0            0.0            1.0
2928            0.0            0.0            0.0            1.0
2929            0.0            0.0            0.0            1.0

      Sale Condition_Abnorml  Sale Condition_AdjLand  Sale Condition_Alloca  \
0                        0.0                     0.0                    0.0
1                        0.0                     0.0                    0.0
2                        0.0                     0.0                    0.0
3                        0.0                     0.0                    0.0
4                        0.0                     0.0                    0.0
...                      ...                     ...                    ...
2925                     0.0                     0.0                    0.0
2926                     0.0                     0.0                    0.0
2927                     0.0                     0.0                    0.0
2928                     0.0                     0.0                    0.0
2929                     0.0                     0.0                    0.0

      Sale Condition_Family  Sale Condition_Normal  Sale Condition_Partial
0                       0.0                    1.0                     0.0
1                       0.0                    1.0                     0.0
2                       0.0                    1.0                     0.0
3                       0.0                    1.0                     0.0
4                       0.0                    1.0                     0.0
...                     ...                    ...                     ...
2925                    0.0                    1.0                     0.0
2926                    0.0                    1.0                     0.0
2927                    0.0                    1.0                     0.0
2928                    0.0                    1.0                     0.0
2929                    0.0                    1.0                     0.0

[2930 rows x 306 columns]

In [95]:

# 3. حساب المسافة بين المنزل 0 وجميع المنازل الأخرى
target_house = df_scaled.loc[[0]] # المنزل رقم 0
distances = ps(df_scaled, target_house) # حساب المسافة للكل
print(f"target_house \n{target_house} \n {"*"*20} distances{"*"*20}:\n{distances} ")

target_house
   Order  PID  MS SubClass  Lot Frontage  Lot Area  Overall Qual  \
0    0.0  0.0          0.0      0.450479   0.14242      0.555556

   Overall Cond  Year Built  Year Remod/Add  Mas Vnr Area  ...  Sale Type_New  \
0           0.5    0.637681        0.166667          0.07  ...            0.0

   Sale Type_Oth  Sale Type_VWD  Sale Type_WD   Sale Condition_Abnorml  \
0            0.0            0.0            1.0                     0.0

   Sale Condition_AdjLand  Sale Condition_Alloca  Sale Condition_Family  \
0                     0.0                    0.0                    0.0

   Sale Condition_Normal  Sale Condition_Partial
0                    1.0                     0.0

[1 rows x 306 columns]
 ******************** distances********************:
[[0.        ]
 [5.62886571]
 [4.82922812]
 ...
 [6.40697269]
 [5.99672516]
 [6.18962799]]

In [96]:
# إضافة عمود المسافة والسعر الحقيقي للبيانات للمقارنة
results = df_h.copy()
results['distance_to_0'] = distances
results = results[['SalePrice', 'distance_to_0', 'Gr Liv Area', 'Neighborhood']]
print(results)

      SalePrice  distance_to_0  Gr Liv Area Neighborhood
0        215000       0.000000         1656        NAmes
1        105000       5.628866          896        NAmes
2        172000       4.829228         1329        NAmes
3        244000       4.641716         2110        NAmes
4        189900       5.593235         1629      Gilbert
...         ...            ...          ...          ...
2925     142500       5.700490         1003      Mitchel
2926     131000       5.874354          902      Mitchel
2927     132000       6.406973          970      Mitchel
2928     170000       5.996725         1389      Mitchel
2929     188000       6.189628         2000      Mitchel

[2930 rows x 4 columns]

In [97]:
 # 4. التصفية: نشتي منازل مشابهة (مسافة قريبة) ولكن أرخص الظروf 😂
house_0_price = results.loc[0, 'SalePrice']
print(f"Price of House 0: {house_0_price}")

Price of House 0: 215000

In [98]:
# ترتيب حسب المسافة (الأقرب فالأبعد) وفلترة الأرخص
similar_cheaper_houses = results[results['SalePrice'] < house_0_price].sort_values('distance_to_0')
similar_cheaper_houses
#4 it's enough as i want.(•_•)

      SalePrice  distance_to_0  Gr Liv Area Neighborhood
2552     137000       4.177316         1008        NAmes
684      132500       4.200323         1148        NAmes
618      167000       4.294222         1644        NAmes
632      176000       4.349154         1329        NAmes
1208     180500       4.411220         1425        NAmes
...         ...            ...          ...          ...
2647     124000       7.208913         1750      OldTown
1321      55000       7.259512         1086      OldTown
2027     136000       7.339758         2526      OldTown
1553      13100       7.436622          733       IDOTRR
2657     137000       7.471287         1928      OldTown

[2211 rows x 4 columns]

In [99]:
# عرض أول 5 منازل مشابهة وأرخص
print(similar_cheaper_houses.head(5))

      SalePrice  distance_to_0  Gr Liv Area Neighborhood
2552     137000       4.177316         1008        NAmes
684      132500       4.200323         1148        NAmes
618      167000       4.294222         1644        NAmes
632      176000       4.349154         1329        NAmes
1208     180500       4.411220         1425        NAmes